#python matacq_allFEDs.py --var "Amplitude" --var "tstart"
#python matacq_allFEDs.py --var "Amplitude" --var "tmax"
#python matacq_allFEDs.py --var "Amplitude" --var "riseTime"

python matacq_allFEDs.py --var "Amplitude"
python matacq_allFEDs.py --var "riseTime"
python matacq_allFEDs.py --var "width50"
python matacq_allFEDs.py --var "width10"
python matacq_allFEDs.py --var "width5"
python matacq_allFEDs.py --var "integral"
python matacq_allFEDs.py --var "integral100"
python matacq_allFEDs.py --var "integral250"
python matacq_allFEDs.py --var "integral500"
python matacq_allFEDs.py --var "integral750"
python matacq_allFEDs.py --var "tmax"
python matacq_allFEDs.py --var "tstart"
